
create table
  public.game_plans (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    match_details jsonb,
    team_analysis jsonb,
    opponent_plan jsonb,
    tactics jsonb,
    user_id uuid references auth.users not null,
    ai_generated_plan text,
    constraint game_plans_pkey primary key (id)
  );

alter table game_plans enable row level security;

create policy "Enable read access for all users" on game_plans
  for select using (true);

create policy "Enable insert access for authenticated users only" on game_plans
  for insert with check (auth.role() = 'authenticated');
